DELETE http://localhost:3003/api/blogs/60e343a94cb7f02504d658da
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5lbGxpIiwiaWQiOiI2MGUzMjdkMmJmM2ZlMTA4Zjg1ZGUwZDkiLCJpYXQiOjE2MjU1MDY3MDgsImV4cCI6MTYyNTUxMDMwOH0.6Fp4APivDp5cSG6zxqHYdr06mnwQTP4tJ_PmAF6OlOo